services:
  pulse:
    image: xhh1128/pulse:test
    container_name: pulse-monitor
    ports:
      - "8008:8008"
    volumes:
      # - pulse-data:/app/data
      - ../pulse-data:/app/data
    restart: unless-stopped
