services:
  pulse:
    image: xhh1128/pulse:latest
    container_name: pulse-monitor
    ports:
      - 8008:8008
    volumes:
      - pulse-data:/app/data
    restart: unless-stopped
    networks:
      - pulse-network

volumes:
  pulse-data:

networks:
  pulse-network:
    enable_ipv6: true
    ipam:
      driver: default